# Generated by Django 5.2.17 on 2026-08-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cavallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razza', models.CharField(blank=True, max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('sesso', models.CharField(blank=True, max_length=20)),
                ('microchip', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('scuola', 'Cavallo di scuola'), ('pensione', 'Cavallo in pensione')], default='scuola', max_length=10)),
                ('livello_impiego', models.CharField(choices=[('principianti', 'Principianti'), ('intermedio', 'Intermedio'), ('avanzato', 'Avanzato'), ('riposo', 'A riposo')], default='intermedio', max_length=20)),
                ('disponibile', models.BooleanField(default=True)),
                ('note_disponibilita', models.CharField(blank=True, max_length=255)),
                ('box', models.CharField(blank=True, help_text='Solo per cavalli in pensione.', max_length=50)),
                ('note_sanitarie', models.TextField(blank=True, help_text='Vaccinazioni, sverminazioni, ferrature, veterinario...')),
                ('proprietario', models.ForeignKey(blank=True, help_text='Solo per cavalli in pensione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalli', to='persone.proprietario')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
