# Generated by Django 5.2.17 on 2026-08-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cavallo',
            options={'ordering': ['nome'], 'verbose_name': 'cavallo', 'verbose_name_plural': 'cavalli'},
        ),
    ]
