# Generated by Django 5.2.17 on 2026-08-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalli', '0002_alter_cavallo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavallo',
            name='note_sanitarie',
            field=models.TextField(blank=True, help_text="Note libere aggiuntive. Le scadenze da tenere sotto controllo vanno in 'Scadenze sanitarie' qui sotto, non qui: solo così generano un promemoria automatico."),
        ),
        migrations.CreateModel(
            name='ScadenzaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vaccinazione', 'Vaccinazione'), ('sverminazione', 'Sverminazione'), ('ferratura', 'Ferratura'), ('visita_veterinaria', 'Visita veterinaria'), ('altro', 'Altro')], default='altro', max_length=30)),
                ('data_scadenza', models.DateField(verbose_name='Prossima scadenza')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cavallo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze_sanitarie', to='cavalli.cavallo')),
            ],
            options={
                'verbose_name': 'scadenza sanitaria',
                'verbose_name_plural': 'scadenze sanitarie',
                'ordering': ['data_scadenza'],
            },
        ),
    ]
