# Generated by Django 5.2.17 on 2026-08-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenotazione_autonoma_abilitata', models.BooleanField(default=False, help_text='Se attivo, gli allievi possono prenotare/annullare da soli la propria partecipazione alle lezioni aperte dal portale. Se disattivo (default), le lezioni restano gestite solo da admin/segreteria.', verbose_name='Prenotazione autonoma allievi abilitata')),
                ('email_notifiche_staff', models.EmailField(blank=True, help_text='Destinatario degli alert automatici che non riguardano un allievo specifico (es. scadenze sanitarie dei cavalli). Se vuoto, quegli alert non vengono inviati.', max_length=254, verbose_name='Email notifiche staff')),
                ('notifiche_telegram_abilitate', models.BooleanField(default=False, help_text='Richiede TELEGRAM_BOT_TOKEN configurato nel .env (vedi README).', verbose_name='Notifiche Telegram abilitate')),
                ('notifiche_whatsapp_abilitate', models.BooleanField(default=False, help_text="Richiede un account WhatsApp Business Cloud API (Meta) configurato nel .env — questa piattaforma fornisce solo l'integrazione, non l'account (vedi README).", verbose_name='Notifiche WhatsApp abilitate')),
            ],
            options={
                'verbose_name': 'impostazioni',
                'verbose_name_plural': 'impostazioni',
            },
        ),
    ]
