# Generated by Django 5.2.17 on 2026-08-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cavalli', '0001_initial'),
        ('pacchetti', '0001_initial'),
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoLezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('durata_default_minuti', models.PositiveIntegerField(default=60)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('stato', models.CharField(choices=[('prenotata', 'Prenotata'), ('confermata', 'Confermata'), ('svolta', 'Svolta'), ('annullata', 'Annullata')], default='prenotata', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lezioni', to='lezioni.campo')),
                ('istruttore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lezioni', to='persone.istruttore')),
            ],
            options={
                'ordering': ['data', 'ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('prevista', 'Prevista'), ('svolta', 'Svolta'), ('assente', 'Assente'), ('annullata', 'Annullata')], default='prevista', max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='persone.allievo')),
                ('cavallo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partecipazioni', to='cavalli.cavallo')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='lezioni.lezione')),
                ('pacchetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partecipazioni', to='pacchetti.pacchetto')),
            ],
            options={
                'ordering': ['lezione'],
                'unique_together': {('lezione', 'allievo')},
            },
        ),
        migrations.AddField(
            model_name='lezione',
            name='allievi',
            field=models.ManyToManyField(related_name='lezioni', through='lezioni.Partecipazione', to='persone.allievo'),
        ),
        migrations.AddField(
            model_name='lezione',
            name='tipo_lezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lezioni', to='lezioni.tipolezione'),
        ),
    ]
