# Generated by Django 5.2.17 on 2026-08-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['nome'], 'verbose_name': 'campo', 'verbose_name_plural': 'campi'},
        ),
        migrations.AlterModelOptions(
            name='lezione',
            options={'ordering': ['data', 'ora_inizio'], 'verbose_name': 'lezione', 'verbose_name_plural': 'lezioni'},
        ),
        migrations.AlterModelOptions(
            name='partecipazione',
            options={'ordering': ['lezione'], 'verbose_name': 'partecipazione', 'verbose_name_plural': 'partecipazioni'},
        ),
        migrations.AlterModelOptions(
            name='tipolezione',
            options={'ordering': ['nome'], 'verbose_name': 'tipo di lezione', 'verbose_name_plural': 'tipi di lezione'},
        ),
    ]
