# Generated by Django 5.2.17 on 2026-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0002_alter_campo_options_alter_lezione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipolezione',
            name='capienza_max',
            field=models.PositiveIntegerField(blank=True, help_text="Numero massimo di allievi per una lezione di questo tipo. Lasciare vuoto per nessun limite. Usata solo per la prenotazione autonoma degli allievi dal portale — l'admin può sempre aggiungere partecipanti oltre il limite dal form lezione.", null=True, verbose_name='Capienza massima'),
        ),
    ]
