# Generated by Django 5.2.17 on 2026-08-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0003_tipolezione_capienza_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partecipazione',
            name='pacchetto',
        ),
    ]
