# Generated by Django 5.2.17 on 2026-08-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPacchetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_lezioni', models.PositiveIntegerField()),
                ('durata_giorni', models.PositiveIntegerField(default=30)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, help_text='Solo di riferimento/consultazione: nessuna fatturazione o incasso viene tracciato.', max_digits=8, null=True)),
                ('prezzo_scontato_pensione', models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo di riferimento per i proprietari di cavalli in pensione.', max_digits=8, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero_lezioni'],
            },
        ),
        migrations.CreateModel(
            name='Pacchetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_scadenza', models.DateField()),
                ('lezioni_totali', models.PositiveIntegerField()),
                ('lezioni_utilizzate', models.PositiveIntegerField(default=0)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('scaduto', 'Scaduto'), ('in_pausa', 'In pausa')], default='attivo', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacchetti', to='persone.allievo')),
                ('tipo_pacchetto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacchetti_assegnati', to='pacchetti.tipopacchetto')),
            ],
            options={
                'ordering': ['-data_inizio'],
            },
        ),
    ]
