# Generated by Django 5.2.17 on 2026-08-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacchetti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacchetto',
            options={'ordering': ['-data_inizio'], 'verbose_name': 'pacchetto', 'verbose_name_plural': 'pacchetti'},
        ),
        migrations.AlterModelOptions(
            name='tipopacchetto',
            options={'ordering': ['numero_lezioni'], 'verbose_name': 'tipo di pacchetto', 'verbose_name_plural': 'tipi di pacchetto'},
        ),
    ]
