# Generated by Django 5.2.17 on 2026-08-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacchetti', '0002_alter_pacchetto_options_alter_tipopacchetto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacchetto',
            name='lezioni_utilizzate',
        ),
    ]
