# Generated by Django 5.2.17 on 2026-08-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tutore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('relazione', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('altro', 'Altro')], default='altro', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Allievo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('ex', 'Ex allievo')], default='attivo', max_length=10)),
                ('certificato_medico_tipo', models.CharField(blank=True, choices=[('non_agonistico', 'Non agonistico'), ('agonistico', 'Agonistico')], max_length=20)),
                ('certificato_medico_scadenza', models.DateField(blank=True, null=True)),
                ('tessera_fise_numero', models.CharField(blank=True, max_length=50, verbose_name='N. tessera FISE')),
                ('tessera_fise_scadenza', models.DateField(blank=True, null=True, verbose_name='Scadenza tessera FISE')),
                ('tessera_fitetrek_numero', models.CharField(blank=True, max_length=50, verbose_name='N. tessera FITETREK')),
                ('tessera_fitetrek_scadenza', models.DateField(blank=True, null=True, verbose_name='Scadenza tessera FITETREK')),
                ('consenso_privacy', models.BooleanField(default=False)),
                ('consenso_foto_video', models.BooleanField(default=False)),
                ('propensione', models.CharField(blank=True, help_text="Verso cosa punta l'allievo: salto, dressage, passeggiata, ecc.", max_length=100)),
                ('note_particolari', models.TextField(blank=True, help_text='Ippoterapia, disabilità, allergie, paure, ecc.')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.OneToOneField(blank=True, help_text='Account per il portale di sola lettura, se attivato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allievo', to=settings.AUTH_USER_MODEL)),
                ('tutori', models.ManyToManyField(blank=True, related_name='allievi', to='persone.tutore')),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificato_medico', 'Certificato medico'), ('tessera_fise', 'Tessera FISE'), ('tessera_fitetrek', 'Tessera FITETREK'), ('altro', 'Altro')], default='altro', max_length=30)),
                ('file', models.FileField(upload_to='documenti/%Y/%m/')),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='persone.allievo')),
            ],
            options={
                'ordering': ['-caricato_il'],
            },
        ),
        migrations.CreateModel(
            name='Istruttore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note_disponibilita', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('utente', models.OneToOneField(blank=True, help_text='Account di accesso collegato, se ha un login proprio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istruttore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
