# Generated by Django 5.2.17 on 2026-08-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allievo',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'allievo', 'verbose_name_plural': 'allievi'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-caricato_il'], 'verbose_name': 'documento', 'verbose_name_plural': 'documenti'},
        ),
        migrations.AlterModelOptions(
            name='istruttore',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'istruttore', 'verbose_name_plural': 'istruttori'},
        ),
        migrations.AlterModelOptions(
            name='proprietario',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'proprietario', 'verbose_name_plural': 'proprietari'},
        ),
        migrations.AlterModelOptions(
            name='tutore',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'tutore', 'verbose_name_plural': 'tutori'},
        ),
    ]
