# Generated by Django 5.2.17 on 2026-08-26 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0002_alter_allievo_options_alter_documento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='utente',
            field=models.OneToOneField(blank=True, help_text='Account per il portale di sola lettura sul proprio cavallo, se attivato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
