# Generated by Django 5.2.17 on 2026-08-26 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0003_proprietario_utente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privacy', 'Trattamento dati personali'), ('foto_video', 'Liberatoria foto/video')], max_length=20)),
                ('accettato_il', models.DateTimeField(auto_now_add=True)),
                ('indirizzo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('testo_accettato', models.TextField(help_text="Copia esatta del testo mostrato al momento dell'accettazione.")),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensi', to='persone.allievo')),
            ],
            options={
                'verbose_name': 'consenso accettato',
                'verbose_name_plural': 'consensi accettati',
                'ordering': ['-accettato_il'],
            },
        ),
    ]
