# Generated by Django 5.2.17 on 2026-08-27 08:09

import persone.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persone', '0004_consensolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(help_text='Solo PDF o immagini (JPG/PNG), max 10 MB.', upload_to='documenti/%Y/%m/', validators=[persone.validators.valida_tipo_documento, persone.validators.valida_dimensione_documento]),
        ),
    ]
