# Generated by Django 5.2.17 on 2026-08-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persone', '0002_alter_allievo_options_alter_documento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('inviata_il', models.DateTimeField(blank=True, null=True)),
                ('destinatari_count', models.PositiveIntegerField(default=0)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('inviata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicazioni_inviate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comunicazione',
                'verbose_name_plural': 'comunicazioni',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='NotificaInviata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('promemoria_lezione', 'Promemoria lezione'), ('scadenza_certificato', 'Scadenza certificato medico'), ('scadenza_fise', 'Scadenza tessera FISE'), ('scadenza_fitetrek', 'Scadenza tessera FITETREK'), ('scadenza_pacchetto', 'Scadenza pacchetto')], max_length=30)),
                ('riferimento', models.DateField(help_text="Data a cui si riferisce l'avviso (lezione o scadenza).")),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('allievo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_inviate', to='persone.allievo')),
            ],
            options={
                'verbose_name': 'notifica inviata',
                'verbose_name_plural': 'notifiche inviate',
                'ordering': ['-creata_il'],
                'unique_together': {('tipo', 'allievo', 'riferimento')},
            },
        ),
    ]
