# Generated by Django 5.2.17 on 2026-08-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicazioni', '0001_initial'),
        ('persone', '0002_alter_allievo_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_update_id', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'stato polling Telegram',
                'verbose_name_plural': 'stato polling Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('codice_collegamento', models.CharField(blank=True, help_text="Codice mostrato all'allievo nel portale, da inviare al bot per collegare l'account.", max_length=12)),
                ('collegato_il', models.DateTimeField(blank=True, null=True)),
                ('allievo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='persone.allievo')),
            ],
            options={
                'verbose_name': 'collegamento Telegram',
                'verbose_name_plural': 'collegamenti Telegram',
            },
        ),
    ]
