# Generated by Django 5.2.17 on 2026-08-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalli', '0003_alter_cavallo_note_sanitarie_scadenzasanitaria'),
        ('comunicazioni', '0002_telegrampollstate_telegramlink'),
        ('persone', '0002_alter_allievo_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificainviata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificainviata',
            name='cavallo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_inviate', to='cavalli.cavallo'),
        ),
        migrations.AlterField(
            model_name='notificainviata',
            name='allievo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_inviate', to='persone.allievo'),
        ),
        migrations.AlterField(
            model_name='notificainviata',
            name='tipo',
            field=models.CharField(choices=[('promemoria_lezione', 'Promemoria lezione'), ('scadenza_certificato', 'Scadenza certificato medico'), ('scadenza_fise', 'Scadenza tessera FISE'), ('scadenza_fitetrek', 'Scadenza tessera FITETREK'), ('scadenza_pacchetto', 'Scadenza pacchetto'), ('scadenza_sanitaria_cavallo', 'Scadenza sanitaria cavallo')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='notificainviata',
            unique_together={('tipo', 'allievo', 'cavallo', 'riferimento')},
        ),
    ]
